Completely restructured CustomActions component as a function component instead of class component
-Previously as a class component, I was getting an error: 'this.actionSheet()...is not a function'.
-Spent hours reworking the code, looking at Expo snacks (the CF snack example worked for me when I ran it in a separate folder, but I still got the error using the same syntax as in the example).
-Tried deleting node_modules folder and package-lock.json and reinstalling npm, but couldn't resolve it yet
-Downgrading to Expo v44.0.0 didn't work either